-- PostgreSQL schema for GreenSwampApp
-- Run with: psql -U postgres -d splab5 -f schema.postgres.sql

BEGIN;

-- Optional: make script re-runnable during development
DROP VIEW IF EXISTS trending_ponds;

DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS auth CASCADE;
DROP TABLE IF EXISTS interactions CASCADE;
DROP TABLE IF EXISTS post_tags CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS posts CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- Users table
CREATE TABLE users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    display_name TEXT NOT NULL,
    avatar_url TEXT,
    bio TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE
);

-- Posts table (with embedded media)
CREATE TABLE posts (
    post_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    post_type TEXT NOT NULL CHECK (post_type IN ('text', 'image', 'video')),
    media_url TEXT,
    media_type TEXT CHECK (media_type IN ('image', 'video')),
    alt_text TEXT,
    thumbnail_url TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    parent_post_id INTEGER REFERENCES posts(post_id),

    -- Media validation constraint
    CHECK (
        (post_type = 'text' AND media_url IS NULL) OR
        (post_type IN ('image', 'video') AND media_url IS NOT NULL)
    )
);

-- Tags table
CREATE TABLE tags (
    tag_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_name TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usage_count INTEGER DEFAULT 0
);

-- Post-tags junction table
CREATE TABLE post_tags (
    post_id INTEGER REFERENCES posts(post_id) ON DELETE CASCADE,
    tag_id INTEGER REFERENCES tags(tag_id) ON DELETE CASCADE,
    PRIMARY KEY (post_id, tag_id)
);

-- Interactions table
CREATE TABLE interactions (
    interaction_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    post_id INTEGER NOT NULL REFERENCES posts(post_id) ON DELETE CASCADE,
    interaction_type TEXT NOT NULL CHECK (
        interaction_type IN ('comment', 'reribb', 'like', 'rsvp')
    ),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    content TEXT,
    UNIQUE(user_id, post_id, interaction_type)
);

-- Events table
CREATE TABLE events (
    event_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id INTEGER UNIQUE REFERENCES posts(post_id) ON DELETE CASCADE,
    event_time TIMESTAMP NOT NULL,
    location TEXT NOT NULL,
    host_org TEXT,
    rsvp_count INTEGER DEFAULT 0,
    max_capacity INTEGER
);

-- Authentication table
CREATE TABLE auth (
    user_id INTEGER PRIMARY KEY REFERENCES users(user_id) ON DELETE CASCADE,
    password_hash TEXT NOT NULL,
    last_login TIMESTAMP,
    reset_token TEXT,
    token_expiry TIMESTAMP
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_posts_created ON posts(created_at);
CREATE INDEX IF NOT EXISTS idx_posts_type ON posts(post_type);
CREATE INDEX IF NOT EXISTS idx_interactions_type ON interactions(interaction_type);
CREATE INDEX IF NOT EXISTS idx_tags_name ON tags(tag_name);
CREATE INDEX IF NOT EXISTS idx_events_time ON events(event_time);

-- Trending ponds view (last 24 hours)
CREATE VIEW trending_ponds AS
SELECT
    t.tag_id,
    t.tag_name,
    COUNT(pt.post_id) AS recent_posts
FROM tags t
JOIN post_tags pt ON t.tag_id = pt.tag_id
JOIN posts p ON pt.post_id = p.post_id
WHERE p.created_at > (now() - interval '1 day')
GROUP BY t.tag_id, t.tag_name
ORDER BY recent_posts DESC
LIMIT 10;

COMMIT;
